'use strict'

export const LOGIN_DOING = 'LOGIN_DOING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOCATING = 'LOCATING';
export const LOCATE_SUCCESS = 'LOCATE_SUCCESS';
export const LOCATE_ERROR = 'LOCATE_ERROR';
export const LOCATING_STORE = 'LOCATING_STORE';
export const LOCATE_STORE_SUCCESS = 'LOCATE_STORE_SUCCESS';
export const LOCATE_STORE_ERROR = 'LOCATE_STORE_ERROR';